# Generated by Django 5.0.2 on 2025-05-28 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'Общие'), ('political', 'Политические'), ('family', 'Семейные'), ('work', 'Рабочие'), ('student', 'Студенческие'), ('medical', 'Медицинские'), ('programming', 'Про программистов')], default='general', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
