# Generated by Django 5.0.2 on 2025-05-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joke',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
